#!/bin/bash
if ! command -v wget > /dev/null 2>&1; then
    echo "wget is not installed but is needed for the program to work."
    exit 1
fi
KEEP=false
YES=false
GLOBAL=true
while [ $# -ne 0 ]; do
    case "$1" in
        -h | --help)
            echo -e "pwsh-update: Update/install PowerShell on Linux distros
Usage:
-h | --help
    Print a help message and exit.

-k | --keep
    Keep the downloaded archive after installation.

-y | --yes
    Answer \"y\" for everything.

-u | --user
    Only install for user."
            exit
            ;;
        -k | --keep)
            KEEP=true
            ;;
        -y | --yes)
            YES=true
            ;;
        -u | --user)
            GLOBAL=false
            ;;
        *)
            echo "\"$1\": invalid option. Run \"pwsh-update --help\" to see all options."
            exit 1
            ;;
    esac
    shift
done
if [ $EUID != 0 ] && [ $GLOBAL = "true" ]; then
    echo "Please run this script as root or with sudo."
    exit 1
fi
case $(arch) in
    aarch64)
        ARCH="arm64"
        ;;
    arm)
        ARCH="arm32"
        ;;
    x86_64 | amd64)
        ARCH="x64"
        ;;
    *)
        echo "Architecture $(arch) not supported."
        exit 1
        ;;
esac
LATEST=$(wget -qO- https://github.com/PowerShell/PowerShell/releases/latest | grep -oh "<title>.*</title>" | tr " " "\n" | grep "^v.*$" | tr -d "v")
if [ "$LATEST" = "" ]; then
    echo "Failed to get latest PowerShell version."
    exit 1
fi
if [ $GLOBAL = "true" ]; then
    if command -v pwsh > /dev/null 2>&1; then
        if [ "$LATEST" = "$(pwsh -v | tr -d "PowerShell ")" ]; then
            echo "PowerShell is already the newest version ($LATEST)."
            exit
        else
            echo -n "PowerShell version ($LATEST) is released! Update? [y/n] "
        fi
    else
        echo -n "PowerShell is not installed. Install? [y/n] "
    fi
else
    if command -v ~/powershell/pwsh > /dev/null 2>&1; then
        if [ "$LATEST" = "$(~/powershell/pwsh -v | tr -d "PowerShell ")" ]; then
            echo "PowerShell is already the newest version ($LATEST)."
            exit
        else
            echo -n "PowerShell version ($LATEST) is released! Update? [y/n] "
        fi
    else
        echo -n "PowerShell is not installed. Install? [y/n] "
    fi
fi
if [ $YES = "true" ]; then
    CHOICE="Y"
    echo "y"
else
    read CHOICE
fi
if [ "${CHOICE^^}" = "N" ]; then
    echo "Abort."
else
    TARFILE=$(mktemp /tmp/powershell-XXXXXX.tar.gz)
    echo "Downloading PowerShell ($LATEST)..."
    if wget "https://github.com/PowerShell/PowerShell/releases/download/v$LATEST/powershell-$LATEST-linux-$ARCH.tar.gz" -O "$TARFILE" > /dev/null 2>&1; then
        echo "Download done."
    else
        echo "Download failed."
        exit 1
    fi
    echo "Extracting files..."
    if [ $GLOBAL = "true" ]; then
        if rm -rf /usr/local/lib/powershell > /dev/null 2>&1; mkdir -p /usr/local/lib/powershell > /dev/null 2>&1; tar -zxf "$TARFILE" -C /usr/local/lib/powershell > /dev/null 2>&1; then
            echo "Extraction done."
        else
            echo "Extraction failed."
            exit 1
        fi    
        echo "Linking executable to /usr/local/bin..."
        if ln -sf /usr/local/lib/powershell/pwsh /usr/local/bin/pwsh > /dev/null 2>&1; then
            echo "Linking done. Make sure that /usr/local/bin is in your \$PATH. Run \"pwsh\" to start PowerShell."
        else
            echo "Linking failed."
            exit 1
        fi
    else
        if rm -rf ~/powershell > /dev/null 2>&1; mkdir -p ~/powershell > /dev/null 2>&1; tar -zxf "$TARFILE" -C ~/powershell > /dev/null 2>&1; then
            echo "Extraction done. Run \"~/powershell/pwsh\" to start PowerShell."
        else
            echo "Extraction failed."
            exit 1
        fi
    fi
    
    if [ $KEEP = "true" ]; then
        echo "The archive is stored at \"$TARFILE\". Move it to another directory for later use."
    else
        rm -f "$TARFILE"
    fi
fi
